### ISSUE TITLE
Occur bugs when doing backward process.

### ISSUE THREAD

**Issue by HONGJINLYU** [flaport/torch_sparse_solve#7]
Hi flaport:

Many thanks for your great blog!

However, when I run the backward process, there is some weird problems I cannot solve.
Could you give me some suggestion?

Code:

`

```
import torch
from torch_sparse_solve import solve
torch.manual_seed(42)
from torch.autograd import gradcheck

mask = torch.tensor([[[1, 0, 0], [1, 1, 0], [0, 0, 1]]], dtype=torch.float64)
A = mask * torch.randn(4, 3, 3, dtype=torch.float64)
Asp = A.to_sparse()
Asp.requires_grad_()
b = torch.randn(4, 3, 2, dtype=torch.float64, requires_grad=True)
gradcheck(solve, [Asp, b], check_sparse_nnz=True)`
```

Error:
````
/home/hongjin/anaconda3/envs/20210714colorization/bin/python3 /home/hongjin/PycharmProjects/Year_2021/Colorization_libo/0714_customed_sparse_linear_system_pytorch/test.py
Traceback (most recent call last):
  File "/home/hongjin/PycharmProjects/Year_2021/Colorization_libo/0714_customed_sparse_linear_system_pytorch/test.py", line 60, in <module>
    gradcheck(solve, [Asp, b], check_sparse_nnz=True)
  File "/home/hongjin/anaconda3/envs/20210714colorization/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 478, in gradcheck
    if not check_undefined_grad_support(output_to_check):
  File "/home/hongjin/anaconda3/envs/20210714colorization/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 458, in check_undefined_grad_support
    if (gi is not None) and (not gi.eq(0).all()):
RuntimeError: Could not run 'aten::eq.Scalar' with arguments from the 'SparseCPU' backend. 'aten::eq.Scalar' is only available for these backends: [CPU, CUDA, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/build/aten/src/ATen/CPUType.cpp:2127 [kernel]
CUDA: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/build/aten/src/ATen/CUDAType.cpp:2983 [kernel]
QuantizedCPU: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/build/aten/src/ATen/QuantizedCPUType.cpp:297 [kernel]
BackendSelect: fallthrough registered at /opt/conda/conda-bld/pytorch_1607370169888/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: fallthrough registered at /opt/conda/conda-bld/pytorch_1607370169888/work/aten/src/ATen/core/NamedRegistrations.cpp:11 [kernel]
AutogradOther: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradCPU: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradCUDA: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradXLA: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradPrivateUse1: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradPrivateUse2: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
AutogradPrivateUse3: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/torch/csrc/autograd/generated/VariableType_4.cpp:7586 [autograd kernel]
Tracer: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/torch/csrc/autograd/generated/TraceType_4.cpp:9291 [kernel]
Autocast: fallthrough registered at /opt/conda/conda-bld/pytorch_1607370169888/work/aten/src/ATen/autocast_mode.cpp:254 [backend fallback]
Batched: registered at /opt/conda/conda-bld/pytorch_1607370169888/work/aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
VmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1607370169888/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
```


Process finished with exit code 1
`

Many thanks for your kind help!

HONGJIN

**Comment by flaport** [comment]
Hi @HONGJINLYU ,

My apologies for my late reply.

Apparently in Pytorch 1.6 and beyond you have to add the `check_undefined_grad=False` flag to `gradcheck` as I assume the gradients at the dropped locations is not defined:

```
import torch
from torch_sparse_solve import solve
torch.manual_seed(42)
from torch.autograd import gradcheck

mask = torch.tensor([[[1, 0, 0], [1, 1, 0], [0, 0, 1]]], dtype=torch.float64)
A = mask * torch.randn(4, 3, 3, dtype=torch.float64)
Asp = A.to_sparse()
Asp.requires_grad_()
b = torch.randn(4, 3, 2, dtype=torch.float64, requires_grad=True)
gradcheck(solve, [Asp, b], check_sparse_nnz=True, check_undefined_grad=False)
```
